# SPDX-FileCopyrightText: 2022-2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Run if postgres_backup_postgres_data_path is specified to autodetect the Postgres version
  when: postgres_backup_postgres_data_path != ''
  block:
    - name: Detect Postgres version from provided data path
      ansible.builtin.include_role:
        name: "{{ postgres_backup_postgres_role_include_name }}"
        tasks_from: detect_existing_postgres_version

    # If we have found an existing version (installed from before), we use its corresponding Docker image.
    # If not, we let `postgres_backup_container_image_to_use` remain default (using the latest Postgres version).
    - name: Use detected Postgres version, if detected
      ansible.builtin.set_fact:
        postgres_backup_container_image_to_use: "{{ postgres_backup_detected_version_corresponding_docker_image }}"
      when: postgres_backup_detected_version_corresponding_docker_image | default('') != ''

- name: Ensure postgres-backup paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ postgres_backup_uid }}"
    group: "{{ postgres_backup_gid }}"
  with_items:
    - "{{ postgres_backup_base_path }}"
    - "{{ postgres_backup_config_path }}"
    - "{{ postgres_backup_data_path }}"

- name: Ensure postgres-backup environment variables file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ postgres_backup_config_path }}/env"
    owner: "{{ postgres_backup_uid }}"
    group: "{{ postgres_backup_gid }}"
    mode: "0640"

- name: Ensure postgres-backup Docker image is pulled
  community.docker.docker_image:
    name: "{{ postgres_backup_container_image_to_use }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ postgres_backup_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else postgres_backup_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure postgres-backup container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ postgres_backup_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure postgres-backup systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/postgres-backup.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ postgres_backup_identifier }}.service"
    mode: "0644"
