# SPDX-FileCopyrightText: 2022 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform postgres-backup installation tasks
  block:
    - name: Validate postgres-backup configuration
      when: postgres_backup_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install postgres-backup
      when: postgres_backup_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

    - name: Migrate old postgres-backup
      when: postgres_backup_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install_migrate_old_data.yml"
  tags:
    - setup-all
    - setup-postgres-backup
    - install-all
    - install-postgres-backup

- name: Perform postgres-backup uninstallation tasks
  block:
    - name: Uninstall postgres-backup
      when: not postgres_backup_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-postgres-backup
