# SPDX-FileCopyrightText: 2022-2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required postgres-backup settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "not vars[item]"
  with_items:
    - postgres_backup_connection_hostname
    - postgres_backup_connection_username
    - postgres_backup_connection_password
    - postgres_backup_uid
    - postgres_backup_gid
    - postgres_backup_container_network

- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - { "old": "postgres_backup_container_image_suffix", "new": "postgres_backup_container_image_distro" }
    - { "old": "postgres_backup_path", "new": "postgres_backup_base_path" }
    - { "old": "postgres_backup_docker_image_to_use", "new": "postgres_backup_container_image_to_use" }
